homework
HavierVilson/RecipeBook pull request #1
Opened 2023-01-14 17:26 UTC by HavierVilson

2023-01-19 18:36 UTC, OlgaLugacheva requested changes

2023-01-19 18:36 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipebook/controllers/IngredientsController.java
> +    @GetMapping("/get/{id}")
get из маппинга лучше убрать и так понятно , что get

2023-01-19 18:36 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipebook/controllers/IngredientsController.java
> +    @PutMapping("/edit/{id}")
edit тоже можно убрать

2023-01-19 18:36 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipebook/controllers/IngredientsController.java
> +    @DeleteMapping("/delete/{id}")
delete убрать

2023-01-19 18:36 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipebook/controllers/IngredientsController.java
> +    @GetMapping("/get/all")
get убрать

2023-01-19 18:36 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipebook/controllers/RecipeBookController.java
> +    @GetMapping("/get/{id}")
смотри комментарий про маппинг в другом классе

2023-01-19 18:36 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipebook/controllers/IngredientsController.java
> +    public ResponseEntity<Ingredient> putIngredient(@PathVariable int id, @RequestParam String name, @RequestParam int count, @RequestParam String format) {
вместо RequestParam используй RequestBody и передавай Ingredient

2023-01-19 18:36 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipebook/controllers/RecipeBookController.java
> +    public ResponseEntity<Recipe> putIngredient(@PathVariable int id, @RequestParam String name, @RequestParam int time, @RequestParam ArrayList<Ingredient> ingredients, @RequestParam ArrayList<Strin
вместо RequestParam используй RequestBody и передавай Recipe

2023-01-19 18:36 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipebook/controllers/IngredientsController.java
> +    public ResponseEntity<Ingredient> addIngredient(@RequestParam int id, @RequestParam String name, @RequestParam int count, @RequestParam String format) {
вместо RequestParam используй RequestBody и передавай Ingredient

2023-01-19 18:36 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipebook/controllers/RecipeBookController.java
> +    public ResponseEntity<Recipe> addIngredient(@RequestParam int id, @RequestParam String name, @RequestParam int time, @RequestParam ArrayList<Ingredient> ingredients, @RequestParam ArrayList<Strin
вместо RequestParam используй RequestBody и передавай Recipe

2023-01-20 06:20 UTC, OlgaLugacheva approved these changes

2023-01-26 19:31 UTC, artem-petrosyan commented on src/main/java/pro/sky/recipebook/services/impl/FilesServiceImpl.java
> +    private static String dataFilePath;
В static поля чтение значения не произойдёт. Нужно поправить

2023-01-26 19:31 UTC, artem-petrosyan commented on src/main/java/pro/sky/recipebook/services/impl/FilesServiceImpl.java
> +    private static String ingredientsFileName;
В static поля чтение значения не произойдёт. Нужно поправить

2023-01-26 19:31 UTC, artem-petrosyan commented on src/main/java/pro/sky/recipebook/services/impl/FilesServiceImpl.java
> +    private static String recipesFileName;
В static поля чтение значения не произойдёт. Нужно поправить

2023-01-26 19:31 UTC, artem-petrosyan commented on src/main/java/pro/sky/recipebook/services/impl/FilesServiceImpl.java
> +            return Files.readString(path);
Тут упадёт ошибка, если файла ещё нет

2023-01-26 19:31 UTC, artem-petrosyan commented on src/main/java/pro/sky/recipebook/services/impl/FilesServiceImpl.java
> +            return Files.readString(path);
Тут упадёт ошибка, если файла ещё нет

2023-01-26 19:31 UTC, artem-petrosyan commented on src/main/java/pro/sky/recipebook/services/impl/FilesServiceImpl.java
> +            return false;
Исключения должны выводится через e.printStackTrace()

2023-01-26 19:31 UTC, artem-petrosyan commented on src/main/java/pro/sky/recipebook/services/impl/FilesServiceImpl.java
> +            return false;
Исключения должны выводится через e.printStackTrace()

2023-01-26 19:31 UTC, artem-petrosyan commented on src/main/java/pro/sky/recipebook/services/impl/FilesServiceImpl.java
> +            throw new RuntimeException(e);
Исключения должны выводится через e.printStackTrace()

2023-01-26 19:31 UTC, artem-petrosyan commented on src/main/java/pro/sky/recipebook/services/impl/FilesServiceImpl.java
> +            throw new RuntimeException(e);
Исключения должны выводится через e.printStackTrace()

2023-01-26 19:31 UTC, artem-petrosyan commented on src/main/java/pro/sky/recipebook/services/impl/FilesServiceImpl.java
> +            return false;
Исключения должны выводится через e.printStackTrace()

2023-01-26 19:31 UTC, artem-petrosyan commented on src/main/java/pro/sky/recipebook/services/impl/FilesServiceImpl.java
> +            return false;
Исключения должны выводится через e.printStackTrace()

2023-01-26 19:31 UTC, artem-petrosyan commented on src/main/java/pro/sky/recipebook/services/impl/FilesServiceImpl.java
> +    public String readFromIngredientsFile() {
Метод не вызывается, обрати внимание

2023-01-26 19:31 UTC, artem-petrosyan commented on src/main/java/pro/sky/recipebook/services/impl/FilesServiceImpl.java
> +    public String readFromRecipesFile() {
Метод не вызывается, обрати внимание

2023-01-26 20:12 UTC, artem-petrosyan commented on src/main/java/pro/sky/recipebook/services/impl/FilesServiceImpl.java
> +        } catch (NoSuchFileException e) { //Если я првильно понял то надо было эту ошибку добавить
Можно и так. 
Но тогда обязательно проверь там, где используется этот метод, что вернулось не null.

2023-01-26 20:12 UTC, artem-petrosyan commented on src/main/java/pro/sky/recipebook/services/impl/FilesServiceImpl.java
> +            return null;
Можно и так. 
Но тогда обязательно проверь там, где используется этот метод, что вернулось не null.

2023-01-28 11:53 UTC, merged